# -*- coding: utf-8 -*-
"""Salinan Salinan Finale Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TABtBFcSVNAFwcaHXkQ605p8aJo_Azye

# **PERSIAPAN**

##**Import dan Optimasi data**
"""

# =========================================================
# BLOK 1: PERSIAPAN & DATA LOADING
# =========================================================
import pandas as pd
import numpy as np
from google.colab import drive

# 1. Menghubungkan ke Google Drive
print("Sedang meminta akses ke Google Drive...")
drive.mount('/content/drive')

# 2. Mendefinisikan Lokasi File
# Pastikan path ini benar (Klik ikon folder di kiri -> drive -> MyDrive -> cari file .csv -> klik kanan 'Copy Path')
file_path = '/content/drive/MyDrive/PROJECT DATA SCIENTIS INTERN GOJEK/onlinefraud.csv'

# 3. Membaca Dataset
print("Sedang membaca jutaan baris data... Harap bersabar.")
df = pd.read_csv(file_path)
print("Data berhasil dimuat sempurna!\n")

df.tail()

# 4. Inspeksi Awal (Rapor Kesehatan Data)
print("--- INFO DATA ---")
print(df.info()) # Melihat tipe data dan mengecek apakah ada yang kosong (null)

# Melakukan Downcasting pada tipe Integer
# step dari int64 -> int32
df['step'] = df['step'].astype('int32')
# isFraud dan isFlaggedFraud dari int64 -> int8 (karena isinya cuma 0 dan 1)
df['isFraud'] = df['isFraud'].astype('int8')
df['isFlaggedFraud'] = df['isFlaggedFraud'].astype('int8')

# Note: Kolom float64 tetap kita biarkan utuh

print(df.info())

"""##**Cek Data**"""

print(df.isnull().sum())

print("\n--- STATISTIK DASAR ---")
pd.set_option('display.float_format', lambda x: '%.4f' % x)
display(df.describe()) # Melihat rentang angka pada saldo dan jumlah transfer

"""# **OLAH DATA**

##**FUTURE ENGINER**
"""

# =========================================================
# BLOK 2: FEATURE ENGINEERING (Standard Industri & Anti-Leakage)
# =========================================================
print("Memulai proses rekayasa data... (Mesin Google sedang bekerja)")

# 1. PENGURUTAN WAKTU (Super Krusial untuk simulasi Real-Time)
df = df.sort_values(by=['step'])

# 2. FITUR RASIO KEUANGAN (Aman & Tanpa Leakage)
# Menggunakan data yang HANYA diketahui SAAT transaksi diajukan
print("- Membuat fitur rasio transaksi...")
# Rasio nominal transfer terhadap saldo saat ini (seberapa menguras saldo?)
df['amount_vs_balance_orig'] = np.where(df['oldbalanceOrg'] > 0,
                                        df['amount'] / df['oldbalanceOrg'],
                                        -1) # Gunakan -1 jika saldo 0 untuk bedakan kasus

# 3. EKSTRAKSI POLA WAKTU SIKLIKAL (Jam dalam sehari)
print("- Mengekstrak siklus waktu harian...")
df['transaction_hour'] = df['step'] % 24

# 4. MEMBUANG NOISE & FITUR LEAKAGE
print("- Membuang kolom sampah dan mencegah leakage...")
kolom_sampah = [
    'nameOrig', 'nameDest', 'isFlaggedFraud', 'step',
    'newbalanceOrig', 'newbalanceDest']
df.drop(columns=kolom_sampah, inplace=True)

# 5. ENCODING TIPE TRANSAKSI (AI butuh angka, bukan teks "TRANSFER")
print("- Mengubah kategori transaksi (One-Hot Encoding)...")
df = pd.get_dummies(df, columns=['type'], drop_first=True)

# Mengamankan hasil get_dummies menjadi tipe integer biner (0/1) agar hemat RAM
for col in df.select_dtypes(include=['bool']).columns:
    df[col] = df[col].astype('int8')

print("Bentuk data sekarang (Baris, Kolom):", df.shape)
display(df.head())

"""##**Penggunaan Data**"""

# =========================================================
# BLOK 3 (REVISI): TIME-BASED SPLIT (Anti-Leakage)
# =========================================================
print("Memulai pembagian data kronologis...")

# 1. TIME-BASED SPLIT (Memotong data berdasarkan urutan waktu, TANPA diacak)
# Asumsi: df sudah di-sort_values(by=['step']) di Blok 2
split_index = int(len(df) * 0.8) # 80% untuk Train, 20% untuk Test

# Memisahkan Fitur dan Target secara berurutan
X_train = df.drop(columns=['isFraud']).iloc[:split_index]
y_train = df['isFraud'].iloc[:split_index]

X_test = df.drop(columns=['isFraud']).iloc[split_index:]
y_test = df['isFraud'].iloc[split_index:]

print(f"- Data latih (Masa Lalu): {len(X_train)} baris.")
print(f"- Data uji (Masa Depan): {len(X_test)} baris.")

# KITA TIDAK MELAKUKAN UNDERSAMPLING DI SINI.
# Kita akan menyimpan semua 5 juta data transaksi normal agar model pintar.
# Penyeimbangan (Balancing) akan kita lakukan DI DALAM model pada Blok 4 (menggunakan parameter algoritma).

"""# **ANALISIS**

## **Tuning**
"""

# =========================================================
# FASE 1.5: TUNING XGBOOST + EARLY STOPPING (VERSI BENAR)
# =========================================================
import time
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
from scipy.stats import randint as sp_randint
from scipy.stats import uniform as sp_uniform
from xgboost import XGBClassifier

print("🛠️ FASE 1.5: Tuning XGBoost + Early Stopping...")

# 1. Ambil 30% data terbaru
potongan_data_xgb = int(len(X_train) * 0.30)
X_train_xgb = X_train.iloc[-potongan_data_xgb:]
y_train_xgb = y_train.iloc[-potongan_data_xgb:]

# 2. CV tetap dipakai
tscv = TimeSeriesSplit(n_splits=2)

# 3. Model XGBoost (GPU)
xgb_dasar = XGBClassifier(
    n_estimators=200,
    random_state=42,
    eval_metric='logloss',
    tree_method='hist',
    n_jobs=1
)

# 5. Parameter tuning
param_test_xgb = {
    'max_depth': sp_randint(3, 8),
    'learning_rate': sp_uniform(0.01, 0.15),
    'subsample': sp_uniform(0.6, 0.4),
    'colsample_bytree': sp_uniform(0.6, 0.4),
    'scale_pos_weight': [10, 25, 50]
}

# 6. RandomizedSearch
random_search_xgb = RandomizedSearchCV(
    estimator=xgb_dasar,
    param_distributions=param_test_xgb,
    n_iter=15,
    scoring='average_precision',
    cv=tscv,
    random_state=42,
    n_jobs=1
)

# 7. 🚀 FIT + EARLY STOPPING (INI KUNCINYA)
start_tuning_xgb = time.time()
random_search_xgb.fit(X_train_xgb, y_train_xgb)
waktu_tuning_xgb = time.time() - start_tuning_xgb

best_xgb_params = random_search_xgb.best_params_
print(f"✅ Tuning XGBoost Selesai dalam {waktu_tuning_xgb:.2f} detik!")
print(f"📌 Parameter Terbaik XGBoost: {random_search_xgb.best_params_}\n")

# =========================================================
# BLOK 3.5: TUNING LIGHTGBM
# =========================================================
import time
import lightgbm as lgb
from lightgbm import LGBMClassifier
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

print("🛠️ FASE 1: Tuning LightGBM ")

# 1. Ambil 30% data terbaru
potongan_data = int(len(X_train) * 0.3)
X_train_tuning = X_train.iloc[-potongan_data:]
y_train_tuning = y_train.iloc[-potongan_data:]

# 2. CV tetap dipakai
tscv = TimeSeriesSplit(n_splits=2)

# 4. Model
lgb_dasar = LGBMClassifier(
    n_estimators=200,
    random_state=42,
    verbose=-1,
    n_jobs=-1
)

# 5. Parameter tuning (versi upgrade)
param_test = {
    'num_leaves': sp_randint(20, 60),
    'max_depth': sp_randint(3, 8),
    'learning_rate': sp_uniform(0.01, 0.1),
    'subsample': sp_uniform(0.6, 0.4),
    'colsample_bytree': sp_uniform(0.6, 0.4),
    'min_child_samples': sp_randint(50, 200),
    'scale_pos_weight': [25, 50, 100]
}

# 6. RandomizedSearch
random_search = RandomizedSearchCV(
    estimator=lgb_dasar,
    param_distributions=param_test,
    n_iter=15,
    scoring='average_precision',
    cv=tscv,
    random_state=42,
    n_jobs=1
)

# 7. 🚀 FIT
start_tuning = time.time()
random_search.fit(X_train_tuning, y_train_tuning)
waktu_tuning = time.time() - start_tuning

best_lgb_params = random_search.best_params_
print(f"✅ Tuning Selesai dalam {waktu_tuning:.2f} detik!")
print(f"📌 Parameter Terbaik Ditemukan: {random_search.best_params_}\n")

"""## **Modeling**"""

import time
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    recall_score, accuracy_score, precision_score, f1_score,
    confusion_matrix, roc_auc_score, average_precision_score
)

# =========================================================
# BLOK 4: TRAINING FINAL & EVALUASI (OPTIMAL)
# =========================================================
print("⚔️ FASE 2: TRAINING FINAL (OPTIMAL + EARLY STOPPING + THRESHOLD)\n")

# 🔥 OPTIONAL: hemat RAM & percepat
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')


# =========================================================
# 1. Split validation (untuk early stopping)
# =========================================================
split_index = int(len(X_train) * 0.8)

X_tr = X_train.iloc[:split_index]
y_tr = y_train.iloc[:split_index]

X_val = X_train.iloc[split_index:]
y_val = y_train.iloc[split_index:]

# =========================================================
# 2. Model
# =========================================================
best_lgb_params['n_estimators'] = 500

models = {
    "Random Forest": RandomForestClassifier(
        random_state=42,
        class_weight='balanced',
        max_depth=None,
        min_samples_split=10,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        **best_xgb_params,
        random_state=42,
        eval_metric='logloss',
        tree_method='hist',
        n_jobs=1,
        early_stopping_rounds=50,
        n_estimators=2000,
    ),

    "LightGBM": LGBMClassifier(
        **best_lgb_params,
        random_state=42,
        verbose=-1,
        n_jobs=-1
    )
}

# =========================================================
# ASUMSI BIAYA BISNIS (GLOBAL)
# =========================================================
BIAYA_FN = 1000000  # Rp 100 Ribu jika 1 penipu lolos (Ubah sesuai keinginan)
BIAYA_FP = 50000   # Rp 50 Ribu jika 1 nasabah komplain karena salah blokir (Ubah sesuai keinginan)

# =========================================================
# 3. Threshold tuning function (BERBASIS BIAYA BISNIS)
# =========================================================
def cari_threshold_biaya_terendah(y_true, y_proba):
    thresholds = np.arange(0.1, 0.95, 0.05)

    biaya_minimal = float('inf')
    best_threshold = 0.5

    for t in thresholds:
        y_pred = (y_proba >= t).astype(int)

        # Hitung FP dan FN secara manual
        cm = confusion_matrix(y_true, y_pred)
        fp = cm[0][1]
        fn = cm[1][0]

        # Hitung kerugian uang
        total_biaya = (fn * BIAYA_FN) + (fp * BIAYA_FP)

        if total_biaya < biaya_minimal:
            biaya_minimal = total_biaya
            best_threshold = t

    return best_threshold, biaya_minimal

# =========================================================
# 4. Training + Evaluasi
# =========================================================
papan_skor = []

for nama_model, model in models.items():
    print(f"▶ Training {nama_model}...")
    start_time = time.time()

    # 🔥 Early stopping untuk boosting model
    if nama_model == "XGBoost":
        model.fit(
            X_tr, y_tr,
            eval_set=[(X_val, y_val)],
            verbose=False
        )

    else:
        model.fit(X_tr, y_tr)

    waktu_training = time.time() - start_time

    # =====================================================
    # 🔥 Threshold tuning (pakai validation set)
    # =====================================================
    y_val_proba = model.predict_proba(X_val)[:, 1]
    best_threshold, _ = cari_threshold_biaya_terendah(y_val, y_val_proba)

    # =====================================================
    # Evaluasi di test set
    # =====================================================
    y_test_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_test_proba >= best_threshold).astype(int)

    akurasi = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    presisi = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_test_proba)
    pr_auc = average_precision_score(y_test, y_test_proba)
    cm = confusion_matrix(y_test, y_pred)
    total_biaya_test = (cm[1][0] * BIAYA_FN) + (cm[0][1] * BIAYA_FP)
    avg_cost = total_biaya_test / len(y_test)

    papan_skor.append({
        "Nama Model": nama_model,
        "Waktu (Detik)": round(waktu_training, 2),
        "Threshold": round(best_threshold, 2),
        "Akurasi": akurasi,
        "Recall": recall,
        "Precision": presisi,
        "F1-Score": f1,
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc
    })

    print(f"  ✓ Selesai dalam {waktu_training:.2f} detik")
    print(f"  ✓ Threshold terbaik: {best_threshold:.2f}")
    print(f"  ✓ Total Kerugian Realita: Rp {total_biaya_test:,.0f}")
    print(f"  ✓ Rata-rata Kerugian per Transaksi: Rp {avg_cost:,.2f}")
    print(f"  [Confusion Matrix]:")
    print(f"  Normal (TN): {cm[0][0]} | Salah Tuduh (FP): {cm[0][1]}")
    print(f"  Lolos (FN): {cm[1][0]} | Berhasil Ditangkap (TP): {cm[1][1]}\n")

# =========================================================
# 5. Hasil akhir
# =========================================================
df_skor = pd.DataFrame(papan_skor)

print("🏆 HASIL AKHIR")
display(df_skor.sort_values(by="F1-Score", ascending=False))

# =========================================================
# BLOK 5: VISUALISASI FEATURE IMPORTANCE (MEMBEDAH OTAK AI)
# =========================================================
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

print("Membedah fitur paling penting dari ketiga model...\n")

# Kita ambil Top 10 fitur paling berpengaruh
top_n = 10

# Siapkan kanvas gambar (1 baris, 3 kolom)
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('Top 10 Feature Importance: Apa yang Dilihat AI?', fontsize=16, fontweight='bold', y=1.05)

# Looping untuk setiap model yang sudah dilatih di Blok 4
for i, (nama_model, model) in enumerate(models.items()):

    # 1. Ekstraksi skor kepentingan (feature_importances_)
    if hasattr(model, 'feature_importances_'):
        importances = model.feature_importances_
    else:
        print(f"Model {nama_model} tidak memiliki atribut feature_importances_")
        continue

    # 2. Gabungkan nama kolom dengan skor kepentingannya
    df_imp = pd.DataFrame({
        'Fitur': X_train.columns,
        'Skor Kepentingan': importances
    })

    # 🔥 OPTIMASI 1: Hitung persentase dari TOTAL SEMUA FITUR (Bukan dari top 10 saja)
    total_importance = df_imp['Skor Kepentingan'].sum()
    if total_importance > 0: # Mencegah error pembagian dengan nol
        df_imp['Skor Kepentingan'] = (df_imp['Skor Kepentingan'] / total_importance) * 100

    # 3. Urutkan dari yang skornya paling tinggi, lalu ambil Top 10
    df_imp = df_imp.sort_values(by='Skor Kepentingan', ascending=False).head(top_n)

    # 4. Gambar Grafik Batang (Barplot)
    # 🔥 OPTIMASI 2: Tambahkan hue='Fitur' dan legend=False agar tidak muncul warning Seaborn
    sns.barplot(
        x='Skor Kepentingan',
        y='Fitur',
        data=df_imp,
        ax=axes[i],
        palette='magma',
        hue='Fitur',
        legend=False
    )

    axes[i].set_title(f" {nama_model}", fontsize=14, fontweight='bold')
    axes[i].set_xlabel("Sumbangsih Pengaruh (%)", fontsize=12)
    axes[i].set_ylabel("")
    axes[i].grid(axis='x', linestyle='--', alpha=0.7)

# Rapikan layout dan tampilkan
plt.tight_layout()
plt.show()

# =========================================================
# BLOK 6: SHAP EXPLAINABILITY (SEMUA MODEL)
# =========================================================
import shap
import numpy as np
import matplotlib.pyplot as plt

print("🔍 Analisis SHAP untuk semua model...\n")

# =========================================================
# 1. Sampling biar ringan
# =========================================================
sample_size = 1000

if len(X_test) > sample_size:
    X_sample = X_test.sample(sample_size, random_state=42)
else:
    X_sample = X_test.copy()

# =========================================================
# 2. Loop semua model
# =========================================================
for nama_model, model in models.items():

    print(f"\n==============================")
    print(f"📊 SHAP untuk: {nama_model}")
    print(f"==============================")

    try:
        # =================================================
        # 3. Pilih explainer
        # =================================================
        explainer = shap.TreeExplainer(model)

        # =================================================
        # 4. Hitung SHAP
        # =================================================
        shap_values = explainer(X_sample)

        # =================================================
        # 5. FIX WAJIB (binary classification)
        # =================================================
        if isinstance(shap_values.values, np.ndarray) and len(shap_values.values.shape) == 3:
            shap_values_fixed = shap.Explanation(
                values=shap_values.values[:, :, 1],  # class 1 (fraud)
                base_values=shap_values.base_values[:, 1],
                data=shap_values.data,
                feature_names=X_sample.columns.tolist()
            )
        else:
            shap_values_fixed = shap_values

        # =================================================
        # 6. SUMMARY PLOT
        # =================================================
        print("📊 Summary Plot")
        shap.summary_plot(shap_values_fixed, X_sample, show=False)

        # Tambahkan judul dengan nama model ke dalam gambar
        plt.title(f"SHAP Summary Plot - {nama_model}", fontsize=14, pad=20, fontweight='bold')
        plt.tight_layout() # Biar layoutnya nggak kepotong
        plt.show() # Tampilkan plot setelah diberi judul

        # =================================================
        # 7. BAR PLOT
        # =================================================
        print("📊 Bar Plot")
        shap.plots.bar(shap_values_fixed, max_display=10, show=False)

        # Tambahkan judul dengan nama model ke dalam gambar
        plt.title(f"SHAP Feature Importance - {nama_model}", fontsize=14, pad=20, fontweight='bold')
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"❌ Error di {nama_model}: {e}")